[package]
name = "dizako"
version = "0.2.0"
description = "A Material 3 Expressive dithering studio"
authors = ["Alex"]
edition = "2021"
rust-version = "1.77"

[lib]
name = "dizako_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
