/**
 * Generates the determinism-critical constants shared by BOTH engines:
 *
 *   src/dither/tables.ts      — sRGB→linear LUT (f64) + frozen blue-noise ranks
 *   dither-wasm/src/tables.rs — the same constants as Rust arrays
 *
 * Decimal literals round-trip to the nearest f64 under both ECMAScript's
 * ToNumber and Rust's str::parse<f64>, so committed text is a bitwise-exact
 * contract between languages.
 *
 * Run: pnpm gen:tables
 */
import { execSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

// Transpile the masks module so Node can execute the existing generator.
const tmp = "/tmp/opencode/dizako-masks.mjs";
execSync(`pnpm exec esbuild src/dither/masks.ts --bundle --format=esm --outfile=${tmp}`, {
  cwd: root,
  stdio: "pipe",
});
const masks = await import(tmp);

/** Shortest decimal that parses back to this exact f64, in both languages. */
function f64lit(v) {
  if (!Number.isFinite(v)) return v > 0 || Number.isNaN(v) ? "f64::NAN" : v;
  if (Object.is(v, -0)) return "-0.0";
  let s = v.toExponential(17);
  // Trim to shortest round-tripping representation.
  for (let p = 1; p <= 17; p++) {
    const cand = Number(v.toPrecision(p));
    if (Object.is(cand, v)) {
      s = null;
      let str = String(cand);
      // Rust needs an explicit fractional part or exponent for f64 literals.
      if (!/[.e]/.test(str)) str += ".0";
      return str;
    }
  }
  return s.replace("e", "e");
}

/* ---------------- sRGB→linear -------------------
 * Deliberately NOT a table: the curve has a kink at the threshold and
 * curvature there makes any uniform-grid interpolation lose multiple digits.
 * Both engines instead evaluate it through powShared, which is deterministic
 * by construction (see sharedmath/shared.rs).
 * ----------------------------------------------- */

/* ------------- Frozen 64×64 void-and-cluster blue noise ---------- */

const TILE = 64;
const bn = masks.blueNoise(TILE);
// The generator emits mask VALUES ((rank + 0.5) / n, exactly representable in
// f32); recover integer ranks so the frozen table is the canonical form.
const recoverRank = (v) => Math.round(v * TILE * TILE - 0.5);

/* ------------- Shared-math constants (parity contract) ----------- */

// Factorials up to 22!, computed exactly then reciprocated (nearest f64).
const fact = (n) => {
  let f = 1;
  for (let k = 2; k <= n; k++) f *= k;
  return f;
};

const mathConsts = {
  // radians per degree, and its reciprocal
  PI_OVER_180: Math.PI / 180,
  RAD_TO_DEG: 180 / Math.PI,
  SQRT2: Math.SQRT2,
  LN2: Math.LN2,
  // sin(x) = x · Σ Cs[k]·(x²)^k,  Cs[k] = (-1)^k / (2k+1)!, k = 0..11
  CSIN: Array.from({ length: 12 }, (_, k) => (k % 2 ? -1 : 1) / fact(2 * k + 1)),
  // cos(x) = Σ Cc[k]·(x²)^k,     Cc[k] = (-1)^k / (2k)!,   k = 0..12
  CCOS: Array.from({ length: 13 }, (_, k) => (k % 2 ? -1 : 1) / fact(2 * k)),
  // ln(s) = 2z · Σ Cl[k]·(z²)^k, Cl[k] = 1/(2k+1),          k = 0..12
  CLN: Array.from({ length: 13 }, (_, k) => 1 / (2 * k + 1)),
  // e^f  = Σ Ce[k]·f^k,          Ce[k] = 1/k!,               k = 0..17
  CEXP: Array.from({ length: 18 }, (_, k) => 1 / fact(k)),
};

/* --------------------------- Emit TS ----------------------------- */

const tsHead = `/**
 * GENERATED by tools/gen-tables.mjs — do not edit by hand.
 *
 * These constants are the cross-engine parity contract (WASM_PLAN §4.4):
 * the TypeScript engine and the Rust engine must consume byte-identical
 * data. Decimal literals round-trip to the nearest f64/u16 in both
 * languages, so the committed text IS the contract.
 *
 * Blue-noise hash: sha256:${createHash("sha256").update(Buffer.from(bn.buffer, bn.byteOffset, bn.byteLength)).digest("hex")}
 */

`;

const rankLines = [];
for (let y = 0; y < TILE; y++) {
  const row = [];
  for (let x = 0; x < TILE; x++) row.push(String(recoverRank(bn[y * TILE + x])));
  rankLines.push("  " + row.join(",") + ",");
}

writeFileSync(
  join(root, "src", "dither", "tables.ts"),
  `${tsHead}/** Frozen void-and-cluster tile ranks (values are (rank + 0.5) / ${TILE * TILE}). */
export const BLUE_NOISE_TILE: number[] = [
${rankLines.join("\n")}
];

/* Shared-math constants consumed by both engines via identical literals. */

export const PI_OVER_180 = ${f64lit(mathConsts.PI_OVER_180)};
export const RAD_TO_DEG = ${f64lit(mathConsts.RAD_TO_DEG)};
export const SQRT2 = ${f64lit(mathConsts.SQRT2)};
export const LN2 = ${f64lit(mathConsts.LN2)};
export const CSIN: number[] = [
${mathConsts.CSIN.map((v) => `  ${f64lit(v)},`).join("\n")}
];
export const CCOS: number[] = [
${mathConsts.CCOS.map((v) => `  ${f64lit(v)},`).join("\n")}
];
export const CLN: number[] = [
${mathConsts.CLN.map((v) => `  ${f64lit(v)},`).join("\n")}
];
export const CEXP: number[] = [
${mathConsts.CEXP.map((v) => `  ${f64lit(v)},`).join("\n")}
];
`,
);

/* --------------------------- Emit Rust --------------------------- */

const bnRows = [];
for (let y = 0; y < TILE; y++) {
  const row = [];
  for (let x = 0; x < TILE; x++) row.push(String(recoverRank(bn[y * TILE + x])) + ",");
  bnRows.push("    " + row.join(" "));
}

mkdirSync(join(root, "dither-wasm", "src"), { recursive: true });
writeFileSync(
  join(root, "dither-wasm", "src", "tables.rs"),
  `//! GENERATED by tools/gen-tables.mjs — do not edit by hand.
//! Must stay byte-equivalent to src/dither/tables.ts (parity contract).

/// Frozen void-and-cluster ranks; mask value = (rank + 0.5) / ${TILE * TILE}.0.
pub const BLUE_NOISE_SIDE: usize = ${TILE};
pub const BLUE_NOISE_PIXELS: usize = ${TILE * TILE};

#[rustfmt::skip]
pub const BLUE_NOISE_TILE: [u16; BLUE_NOISE_PIXELS] = [
${bnRows.join("\n")}
];

/* Shared-math constants consumed by both engines via identical literals. */

pub const PI_OVER_180: f64 = ${f64lit(mathConsts.PI_OVER_180)};
pub const RAD_TO_DEG: f64 = ${f64lit(mathConsts.RAD_TO_DEG)};
pub const SQRT2: f64 = ${f64lit(mathConsts.SQRT2)};
pub const LN2: f64 = ${f64lit(mathConsts.LN2)};
pub const CSIN: [f64; 12] = [
${mathConsts.CSIN.map((v) => `    ${f64lit(v)},`).join("\n")}
];
pub const CCOS: [f64; 13] = [
${mathConsts.CCOS.map((v) => `    ${f64lit(v)},`).join("\n")}
];
pub const CLN: [f64; 13] = [
${mathConsts.CLN.map((v) => `    ${f64lit(v)},`).join("\n")}
];
pub const CEXP: [f64; 18] = [
${mathConsts.CEXP.map((v) => `    ${f64lit(v)},`).join("\n")}
];
`,
);

console.log("wrote src/dither/tables.ts and dither-wasm/src/tables.rs");
